### PR TITLE
cumulocity-freshdesk and included global error handling

### PR DESCRIPTION
**Pull request by maam1**
Please verify and approve

### CODE REVIEW

**Comment by maam1** [comment]
Added new example dropbox to send email

**Comment by peterlamar** [comment]
@mangatrai Would you be able to help review this as well?

**Comment by peterlamar** [comment]
Thanks @maam1, will you change the filenames to lowercase and replace the _ with -?

**Comment by mangatrai** [comment]
In Step 11 - if possible please correct spellings of freshdesk also. otherwise everything looks okay to me,

**Comment by maam1** [comment]
I have made the required changes. Can you please verify and approve the changes

**Comment by mangatrai** [comment]
Looks good to me.. @peterlamar i believe branch can be merged unless you see any other issue.

**Comment by peterlamar** [comment]
Looks good to me as well. @mangatrai. I just invited you to the repo and granted merge privileges, merge when ready.

**Comment by mangatrai** [comment]
Completed.

**Pull request merged**
