### PR TITLE
ConvertXMLToJSON&JSOnToXML

### PR DESCRIPTION
**Pull request by maam1**
[CreateTicketInFreshDesk&Slack&Twilio.zip](https://github.com/SoftwareAG/webmethodsio-examples/files/3315947/CreateTicketInFreshDesk.Slack.Twilio.zip)
[ConvertXMlToJSON&JSOnToXML.zip](https://github.com/SoftwareAG/webmethodsio-examples/files/3316068/ConvertXMlToJSON.JSOnToXML.zip)

### CODE REVIEW

**Comment by maam1** [comment]
Submitted from Mamatha

**Comment by maam1** [comment]
I have added total 4 workflows

**Comment by peterlamar** [comment]
A zip file won’t necessarily work in this case. We need detailed readme files in markdown and it is unclear for the developer what to do with the json files in the zip. Check out this example for inspiration:

https://github.com/SoftwareAG/webmethodsio-examples/tree/master/hello-email

Thanks for the submission!

**Comment by maam1** [comment]
ok will create new pull request by making changes

**Pull request closed without merging**
